# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/amazon/rook/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/amazon/rook

PRODUCT_COPY_FILES += \
    vendor/amazon/rook/proprietary/vendor/lib/libcameracustom.so:$(TARGET_COPY_OUT_VENDOR)/lib/libcameracustom.so \
    vendor/amazon/rook/proprietary/vendor/bin/nvram_daemon:$(TARGET_COPY_OUT_VENDOR)/bin/nvram_daemon \
    vendor/amazon/rook/proprietary/etc/audio_device.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/audio_device.xml \
    vendor/amazon/rook/proprietary/vendor/lib/hw/audio.primary_amazon.mt8163.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/audio.primary_amazon.mt8163.so \
    vendor/amazon/rook/proprietary/lib/libasp.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libasp.so \
    vendor/amazon/rook/proprietary/lib/libaspclient.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libaspclient.so \
    vendor/amazon/rook/proprietary/vendor/lib/libaudiocompensationfilter.so:$(TARGET_COPY_OUT_VENDOR)/lib/libaudiocompensationfilter.so \
    vendor/amazon/rook/proprietary/vendor/lib/libaudiocomponentengine.so:$(TARGET_COPY_OUT_VENDOR)/lib/libaudiocomponentengine.so \
    vendor/amazon/rook/proprietary/vendor/lib/libaudiocustparam.so:$(TARGET_COPY_OUT_VENDOR)/lib/libaudiocustparam.so \
    vendor/amazon/rook/proprietary/vendor/lib/libaudiodcrflt.so:$(TARGET_COPY_OUT_VENDOR)/lib/libaudiodcrflt.so \
    vendor/amazon/rook/proprietary/vendor/lib/libaudiosetting.so:$(TARGET_COPY_OUT_VENDOR)/lib/libaudiosetting.so \
    vendor/amazon/rook/proprietary/vendor/lib/libaudiostream.so:$(TARGET_COPY_OUT_VENDOR)/lib/libaudiostream.so \
    vendor/amazon/rook/proprietary/vendor/lib/libaudiostream_jni.so:$(TARGET_COPY_OUT_VENDOR)/lib/libaudiostream_jni.so \
    vendor/amazon/rook/proprietary/vendor/lib/libbessound_hd_mtk.so:$(TARGET_COPY_OUT_VENDOR)/lib/libbessound_hd_mtk.so \
    vendor/amazon/rook/proprietary/vendor/lib/libblisrc.so:$(TARGET_COPY_OUT_VENDOR)/lib/libblisrc.so \
    vendor/amazon/rook/proprietary/vendor/lib/libblisrc32.so:$(TARGET_COPY_OUT_VENDOR)/lib/libblisrc32.so \
    vendor/amazon/rook/proprietary/vendor/lib/libcustom_nvram.so:$(TARGET_COPY_OUT_VENDOR)/lib/libcustom_nvram.so \
    vendor/amazon/rook/proprietary/vendor/lib/libcvsd_mtk.so:$(TARGET_COPY_OUT_VENDOR)/lib/libcvsd_mtk.so \
    vendor/amazon/rook/proprietary/vendor/lib/libfile_op.so:$(TARGET_COPY_OUT_VENDOR)/lib/libfile_op.so \
    vendor/amazon/rook/proprietary/vendor/lib/libmsbc_mtk.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmsbc_mtk.so \
    vendor/amazon/rook/proprietary/vendor/lib/libmtklimiter.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmtklimiter.so \
    vendor/amazon/rook/proprietary/vendor/lib/libmtkplayer.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmtkplayer.so \
    vendor/amazon/rook/proprietary/vendor/lib/libmtkshifter.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmtkshifter.so \
    vendor/amazon/rook/proprietary/vendor/lib/libnvram.so:$(TARGET_COPY_OUT_VENDOR)/lib/libnvram.so \
    vendor/amazon/rook/proprietary/vendor/lib/libnvram_daemon_callback.so:$(TARGET_COPY_OUT_VENDOR)/lib/libnvram_daemon_callback.so \
    vendor/amazon/rook/proprietary/vendor/lib/libnvram_platform.so:$(TARGET_COPY_OUT_VENDOR)/lib/libnvram_platform.so \
    vendor/amazon/rook/proprietary/vendor/lib/libnvramagentclient.so:$(TARGET_COPY_OUT_VENDOR)/lib/libnvramagentclient.so \
    vendor/amazon/rook/proprietary/lib/libsmartvolume.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libsmartvolume.so \
    vendor/amazon/rook/proprietary/vendor/lib/libsmartvolume.so:$(TARGET_COPY_OUT_VENDOR)/lib/libsmartvolume.so \
    vendor/amazon/rook/proprietary/vendor/lib/libspeech_enh_lib.so:$(TARGET_COPY_OUT_VENDOR)/lib/libspeech_enh_lib.so \
    vendor/amazon/rook/proprietary/vendor/firmware/BCM43569A2_001.003.004.0142.0191.hcd:$(TARGET_COPY_OUT_VENDOR)/firmware/BCM43569A2_001.003.004.0142.0191.hcd \
    vendor/amazon/rook/proprietary/vendor/firmware/bcm43569a2-firmware.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/bcm43569a2-firmware.bin \
    vendor/amazon/rook/proprietary/vendor/firmware/bcm43569a2.nvm:$(TARGET_COPY_OUT_VENDOR)/firmware/bcm43569a2.nvm \
    vendor/amazon/rook/proprietary/vendor/etc/audio-algorithms/AFE.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/audio-algorithms/AFE.cfg \
    vendor/amazon/rook/proprietary/vendor/etc/audio-algorithms/EQ.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/audio-algorithms/EQ.cfg \
    vendor/amazon/rook/proprietary/vendor/etc/audio-algorithms/MBCL_1.5W.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/audio-algorithms/MBCL_1.5W.cfg \
    vendor/amazon/rook/proprietary/vendor/etc/audio-algorithms/MBCL_1.5W_Audio.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/audio-algorithms/MBCL_1.5W_Audio.cfg \
    vendor/amazon/rook/proprietary/vendor/etc/audio-algorithms/MBCL_1.5W_Video.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/audio-algorithms/MBCL_1.5W_Video.cfg \
    vendor/amazon/rook/proprietary/vendor/etc/audio-algorithms/MBCL_1W_Audio.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/audio-algorithms/MBCL_1W_Audio.cfg \
    vendor/amazon/rook/proprietary/vendor/etc/audio-algorithms/MBCL_1W_Video.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/audio-algorithms/MBCL_1W_Video.cfg \
    vendor/amazon/rook/proprietary/vendor/etc/audio-algorithms/MBCL_2W.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/audio-algorithms/MBCL_2W.cfg \
    vendor/amazon/rook/proprietary/vendor/etc/audio-algorithms/MBCL_2W_Audio.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/audio-algorithms/MBCL_2W_Audio.cfg \
    vendor/amazon/rook/proprietary/vendor/etc/audio-algorithms/MBCL_2W_Video.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/audio-algorithms/MBCL_2W_Video.cfg \
    vendor/amazon/rook/proprietary/vendor/etc/audio-algorithms/MBCL_VOIP.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/audio-algorithms/MBCL_VOIP.cfg \
    vendor/amazon/rook/proprietary/vendor/etc/audio-algorithms/UserEQ.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/audio-algorithms/UserEQ.cfg \
    vendor/amazon/rook/proprietary/vendor/etc/audio-algorithms/VOIPRxParametricEQ.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/audio-algorithms/VOIPRxParametricEQ.cfg \
    vendor/amazon/rook/proprietary/vendor/etc/audio-algorithms/VOIPTxParametricEQ.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/audio-algorithms/VOIPTxParametricEQ.cfg \
    vendor/amazon/rook/proprietary/vendor/etc/audio-algorithms/coefs_FBF.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/audio-algorithms/coefs_FBF.cfg \
    vendor/amazon/rook/proprietary/vendor/etc/audio-algorithms/coefs_FilterBank_160.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/audio-algorithms/coefs_FilterBank_160.cfg \
    vendor/amazon/rook/proprietary/vendor/etc/audio-algorithms/coefs_FilterBank_640.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/audio-algorithms/coefs_FilterBank_640.cfg \
    vendor/amazon/rook/proprietary/vendor/etc/audio-algorithms/coefs_FilterBank_AnalysisSynthesis_1024.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/audio-algorithms/coefs_FilterBank_AnalysisSynthesis_1024.cfg \
    vendor/amazon/rook/proprietary/vendor/etc/audio-algorithms/coefs_FilterBank_AnalysisSynthesis_1280.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/audio-algorithms/coefs_FilterBank_AnalysisSynthesis_1280.cfg
